x-common-service: &common-service
  build: .
  env_file: backend/settings/.env
  restart: unless-stopped
  depends_on:
    redis:
      condition: service_healthy

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    <<: *common-service
    expose:
      - "8000"
    volumes:
      - sqlite_data:/app/backend/db.sqlite3
      - static_data:/app/backend/static
      - media_data:/app/backend/media
    command: daphne -b 0.0.0.0 -p 8000 settings.asgi:application
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on: -web
    ports:
      - "80:80"
    volumes:
      # my conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # for static and media files read only
      - static_data:/var/www/static:ro
      - media_data:/var/www/media:ro

  celery_worker:
    <<: *common-service
    command: celery -A settings worker -l info

  celery_beat:
    <<: *common-service
    volumes:
      - celery_beat_schedule:/app/celerybeat-schedule
    command: celery -A settings beat -l info --schedule=/app/celerybeat-schedule/celerybeat-schedule

  flower:
    <<: *common-service
    ports:
      - "5555:5555"
    command: celery -A settings flower --basic-auth=${BLOG_FLOWER_USER}:${BLOG_FLOWER_PASSWORD}

volumes:
  sqlite_data:
  celery_beat_schedule:
  static_data:
  media_data:
